$('.owl-carousel').owlCarousel({
    item:2,
    loop:true,
    margin:40,
    nav:false,
    autoplay:false,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:1
        },
        700:{
            items:2
        },
        1000:{
            items:2
        }
    }
})